In [1]:
import numpy as np
import mth433 as mth

In [2]:
def get_h(x):
    """
    We are finding the length of the jth subinterval.
    Input: A vector x
    Output: A vector with distances between the elements of x from j+1 to j
    """
    n = len(x)
    h = []
    for j in range(n-1):
        h_2 = round((x[j+1] - x[j]),5)
        h.append(h_2)
    return h

In [3]:
def get_c(h,y):
    """
    We are finding a column vector made up of our desired coefficients by using Ac = z, where we use h to find A.
    Input(s): The length of the jth subinterval h and an input vector y
    Output: a column matrix c
    """
    n = len(h)
    c = []
    z = np.zeros(n-1)
    A = np.zeros((n-1,n-1))
    
    for j in range(n-1):
        A[j,j] = 2*(h[j] + h[j+1])
        
    for j in range(1,n-1):
        A[j,j-1] = h[j]
        A[j-1,j] = h[j]

    for j in range(n-1):
        z[j] = 3*(((y[j+2] - y[j+1])/h[j+1]) - ((y[j+1] - y[j])/h[j]))

    c = np.linalg.solve(A,z)
    c = np.insert(c,0,0)
    c = np.insert(c,n,0)
    return c

In [4]:
def get_b(c,h,y):
    """
    We are trying to find the coefficient for b, by utilizing c,h,j
    Inputs: We are inputting our y vector, our coefficents for c, and the length of the jth subinterval h
    Output: a column matrix b
    """
    n = len(y)
    b = []
    for j in range(0,n-1):
        b_2 = ((y[j+1] - y[j])/h[j]) - (((2*c[j] + c[j+1])*h[j])/3)
        b.append(b_2)
    return b

In [5]:
def get_d(c,h):
    """
    We are trying to find the coefficient for d, by utilizing c and h 
    Inputs: Our coefficents for c and the length of the jth subinterval h
    Output: a column matrix d
    """
    n = len(y)
    d = []
    for j in range(n-1):
        d_2 = (c[j+1] - c[j])/(3*h[j])
        d.append(d_2)
    return d

In [6]:
def cubic_co(pts):
    """
    A function that inputs an (n+1)x2 matrix pts where the first column are the x-coordinates 
    and the second column is the y-coordinates and outputs a nx4 matrix whose columns are the a,b,c,d coordinates
    Input: A (n+1)x2 matrix (pts)
    Output: A nx4 matrix whose columns are the a,b,c,d coordinates
    """
    n = len(pts)
    x = pts[:,0]
    y = pts[:,1]
    a = np.delete(y, -1)
    h = get_h(x)
    c = get_c(h,y)
    b = get_b(c,h,y)
    d = get_d(c,h)
    c = np.delete(c, -1)
    Q = np.array([a,b,c,d]).T
    return Q

In [7]:
x = np.array([1,1.2,1.4,2,2.3]).T

In [8]:
h = get_h(x)
h

[0.2, 0.2, 0.6, 0.3]

In [9]:
y = np.array([-3,1,2,0,1]).T

In [10]:
c = get_c(h,y)
c

array([  0.        , -52.4691358 , -15.12345679,  16.15226337,
         0.        ])

In [11]:
get_b(c,h,y)

[23.497942386831276,
 13.004115226337449,
 -0.5144032921810715,
 0.10288065843621386]

In [12]:
get_d(c,h)

[-87.44855967078188,
 62.24279835390945,
 17.375400091449478,
 -17.946959304984002]

In [13]:
pts = np.array([[1,1.2,1.4,2,2.3],[-3,1,2,0,1]]).T
pts

array([[ 1. , -3. ],
       [ 1.2,  1. ],
       [ 1.4,  2. ],
       [ 2. ,  0. ],
       [ 2.3,  1. ]])

In [15]:
cubic_co(pts)

array([[ -3.        ,  23.49794239,   0.        , -87.44855967],
       [  1.        ,  13.00411523, -52.4691358 ,  62.24279835],
       [  2.        ,  -0.51440329, -15.12345679,  17.37540009],
       [  0.        ,   0.10288066,  16.15226337, -17.9469593 ]])